# Generated by Django 5.0.4 on 2024-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expriences',
            name='details',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
