# Generated by Django 4.2.14 on 2024-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('details', models.TextField(default=None, max_length=5000)),
                ('date', models.DateField()),
                ('url', models.URLField(default=None)),
                ('image', models.ImageField(default=None, upload_to='media/Certifications/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('details', models.TextField(default=None, max_length=5000)),
                ('date', models.DateField()),
                ('url', models.URLField(default=None)),
                ('image', models.ImageField(default=None, upload_to='media/Hackathons/Images')),
            ],
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.AddField(
            model_name='expriences',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='expriences',
            name='index',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=None, upload_to='media/Projects/Images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='index',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
