# Generated by Django 4.2.14 on 2024-07-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_certifications_hackathons_delete_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expriences',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
