# Generated by Django 5.0.4 on 2024-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_expriences_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=None, upload_to='app/media/images'),
        ),
    ]
