# Generated by Django 5.0.4 on 2024-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
